### ISSUE TITLE
[Profile detail] Tabs shown depending on company/startup choice

### ISSUE THREAD

**Issue by Shushunya** [ita-social-projects/Forum#340]
Profile detail view part of the #316

- backend: after #334 no changes
- frontend: 
- [x] show appropriate tabs when `company` selected (point 2 at #316)
- [x] show appropriate tabs when `startup` selected (point 3 at #316)
- [x] show appropriate tabs when `company` and `startup` selected (point 4 at #316)

**Comment by Lvyshnevska** [comment]
implemented in #323
